apiVersion: v1
kind: ConfigMap
metadata:
  name: git-lab
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: git
    title: "GIT Fundamentos"
    description: "GIT Fundamentos"
    duration: 45m
    image: "linuxtips/girus-devops:0.1"
    tasks:
      - name: "Introdução ao Git e sua História"
        description: "Compreenda o que é o Git, por que foi criado e os conceitos fundamentais do controle de versão distribuído."
        steps:
          - "**O que é o Git?**"
          - "O Git é um sistema de controle de versão distribuído usado para rastrear alterações em arquivos, principalmente código-fonte."
          - "Ele permite que desenvolvedores trabalhem de forma colaborativa e segura em um mesmo projeto."
          - "Cada repositório Git contém todo o histórico do projeto, tornando o trabalho independente de conexão com servidores centrais."
          - "**Principais Objetivos do Git**"
          - "- Alto desempenho, mesmo em projetos grandes"
          - "- Integridade dos dados (uso de hashes SHA-1/SHA-256)"
          - "- Suporte eficiente a trabalho distribuído"
          - "- Facilidade para criar e gerenciar ramificações (branches)"
          - "**Breve História do Git**"
          - "O Git foi criado em 2005 por Linus Torvalds, o criador do kernel Linux."
          - "A comunidade Linux utilizava o sistema proprietário BitKeeper para controle de versão."
          - "Após conflitos de licença, tornou-se necessário desenvolver uma alternativa livre e eficiente."
          - "Linus Torvalds projetou o Git em poucos dias, focando em velocidade e confiabilidade."
          - "**Conceitos Fundamentais do Git**"
          - "- **Repositório (repository)**: Local onde o projeto e seu histórico são armazenados"
          - "- **Commit**: Registro de um conjunto de alterações no projeto"
          - "- **Branch**: Linha independente de desenvolvimento"
          - "- **Merge**: Processo de integrar alterações de diferentes branches"
          - "- **Clone**: Cópia completa de um repositório existente"
          - "**Git e Plataformas Remotas**"
          - "O Git pode ser usado localmente, mas é frequentemente integrado a plataformas remotas."
          - "- GitHub"
          - "- GitLab"
          - "- Bitbucket"
          - "Essas plataformas facilitam colaboração, revisão de código e integração contínua."
          - "A seguir, veremos como utilizar o Git na prática."
          - "**Verifique se o git está instalado para podernos dar continuidade.**"
          - "`git --version`"
        tips:
          - type: "info"
            title: "Dica: Leia o livro GIT PRO para aprofundar o conhecimento"
            content: "https://git-scm.com/book/en/v2"
        validation:
          - command: "test -d / && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "Diretório '/' não foi criado corretamente."

      - name: "Git Fundamentos"
        description: "Criando pasta"
        steps:
          - "**Crie uma pasta com o nome workdir**"
          - "`mkdir projeto`"
          - "**Entre no diretorio**"
          - "`cd workdir`"
          - "**crie uma arquivo com o histórico**"
          - "`history > comando.txt`"
          - "**Configurando as informações do seu usuário**"
          - "`git config --global user.email 'devops@devops.com'`"
          - "`git config --global user.name 'devops'`"
          - "**Inicie o  git**"
          - "`git init`"
          - "**Verifique o status**"
          - "`git status`"
          - "**Informar o arquivo que deverá ser versionado pelo git**"
          - "`git add exemplo.txt`"
          - "**Então gerar o commit do arquivo**"
          - "`git commit -m 'Primeiro commit'`"
          - "Agora podemos ver o log do que foi feito e por quem"
          - "`git log`"
        tips:
          - type: "info"
            title: "Dica: Leia o livro GIT PRO para aprofundar o conhecimento"
            content: "https://git-scm.com/book/en/v2"
        validation:
          - command: "test -d projeto && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "Diretório 'projeto' não foi criado corretamente."
