apiVersion: v1
kind: ConfigMap
metadata:
  name: git-lab
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: git
    title: "GIT"
    description: "GIT Fundamentos"
    duration: 45m
    image: "linuxtips/girus-devops:0.1"
    tasks:
      - name: "Primeiros passos"
        description: "Criando pasta"
        steps:
          - "**Crie uma pasta com o nome workdir**"
          - "`mkdir workdir`"
          - "- `/etc`: Armazena arquivos de configuração do sistema"
          - "- `/var`: Contém dados variáveis como logs e filas"
          - "- `/bin` e `/usr/bin`: Armazenam programas (binários) executáveis"
          - "- `/tmp`: Arquivos temporários, geralmente limpos na reinicialização"
          - "**Localizando-se no Sistema**"
          - "O primeiro passo para navegar eficientemente é saber onde você está atualmente. Para isso, usamos o comando `pwd` (Print Working Directory):"
          - "`pwd`"
          - "Este comando exibe o caminho completo do diretório atual, partindo da raiz `/`."
          - "**Listando Conteúdo de Diretórios**"
          - "Para ver o conteúdo do diretório atual, usamos o comando `ls` (list). Por padrão, ele mostra apenas arquivos não-ocultos em formato simples:"
          - "`ls`"
          - "Para obter informações mais detalhadas e ver arquivos ocultos (que começam com `.`), usamos flags adicionais:"
          - "`ls -la`"
          - "Aqui:"
          - "- `-l` ativa o formato longo, mostrando permissões, proprietário, tamanho, data de modificação, etc."
          - "- `-a` mostra todos os arquivos, incluindo os ocultos"
          - "**Significado das colunas na saída de `ls -l`:**"
          - "1. Tipo de arquivo e permissões (ex: `-rw-r--r--`)"
          - "2. Número de links"
          - "3. Proprietário do arquivo"
          - "4. Grupo do arquivo"
          - "5. Tamanho em bytes"
          - "6. Data e hora da última modificação"
          - "7. Nome do arquivo"
          - "**Criando e Navegando entre Diretórios**"
          - "Para criar um novo diretório, usamos o comando `mkdir` (make directory):"
          - "`mkdir lab-practice`"
          - "Para mudar para este diretório, usamos o comando `cd` (change directory):"
          - "`cd lab-practice`"
          - "Confirme que você está no novo diretório:"
          - "`pwd`"
          - "**Criando Arquivos Vazios**"
          - "O comando `touch` é uma maneira simples de criar arquivos vazios ou atualizar a data de modificação de arquivos existentes:"
          - "`touch file1.txt file2.txt file3.txt`"
          - "Verifique os arquivos criados:"
          - "`ls -l`"
          - "Você verá que os arquivos foram criados com tamanho zero."
          - "**Navegação Avançada**"
          - "Alguns atalhos úteis para navegação:"
          - "- `cd ..`: Move para o diretório pai (um nível acima)"
          - "- `cd ~` ou apenas `cd`: Move para o diretório home do usuário atual"
          - "- `cd -`: Retorna ao diretório anterior (onde estava antes do último cd)"
          - "- `cd /`: Move para o diretório raiz do sistema"
          - "Experimente voltar um nível acima e depois retornar ao diretório de prática:"
          - "`cd ..`"
          - "`pwd`"
          - "`cd lab-practice`"
        tips:
          - type: "info"
            title: "Dica: Atalhos para Completar Nomes"
            content: "A tecla Tab é extremamente útil para autocompletar nomes de arquivos e diretórios. Pressione Tab uma vez para completar automaticamente se houver apenas uma opção, ou duas vezes para ver todas as possibilidades."
          - type: "tip"
            title: "Navegação Rápida"
            content: "Para navegação rápida, você pode combinar múltiplos níveis em um único comando: `cd ../../outro-dir` move dois níveis acima e então para 'outro-dir'."
          - type: "warning"
            title: "Caminhos Absolutos vs Relativos"
            content: "Caminhos que começam com / são absolutos (a partir da raiz), enquanto outros são relativos ao diretório atual. Usar caminhos relativos geralmente torna seus comandos mais portáveis."
        validation:
          - command: "test -d lab-practice && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "Diretório 'lab-practice' não foi criado corretamente."
          - command: "test -f lab-practice/file1.txt && test -f lab-practice/file2.txt && test -f lab-practice/file3.txt && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "Os três arquivos de teste não foram criados corretamente."
